export default defineAppConfig({
  pages: [
    'pages/welcome/index',
    'pages/home/index',
    'pages/login/index',
    'pages/register/index',
    'pages/school-list/index',
    'pages/school-detail/index',
    'pages/major-list/index',
    'pages/major-detail/index',
    'pages/score-analysis/index',
    'pages/major-compare/index',
    'pages/recommend/index',
    'pages/chat/index',
    'pages/profile/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#4f46e5',
    navigationBarTitleText: '高考志愿通',
    navigationBarTextStyle: 'white',
  },
  tabBar: {
    custom: true,
    color: '#8e8e93',
    selectedColor: '#4f46e5',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: 'assets/logo.png',
        selectedIconPath: 'assets/logo.png',
      },
      {
        pagePath: 'pages/major-compare/index',
        text: '专业',
        iconPath: 'assets/logo.png',
        selectedIconPath: 'assets/logo.png',
      },
      {
        pagePath: 'pages/recommend/index',
        text: '推荐',
        iconPath: 'assets/logo.png',
        selectedIconPath: 'assets/logo.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/logo.png',
        selectedIconPath: 'assets/logo.png',
      },
    ],
  },
})
