export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/login/index',
    'pages/register/index',
    'pages/school-list/index',
    'pages/school-detail/index',
    'pages/major-list/index',
    'pages/major-detail/index',
    'pages/score-analysis/index',
    'pages/major-compare/index',
    'pages/recommend/index',
    'pages/chat/index',
    'pages/profile/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#4f46e5',
    navigationBarTitleText: '高考志愿通',
    navigationBarTextStyle: 'white',
    backgroundColor: '#f5f5f5',
    enablePullDownRefresh: false,
    onReachBottomDistance: 50,
  },
  lazyCodeLoading: 'requiredComponents',
  tabBar: {
    custom: true,
    color: '#8e8e93',
    selectedColor: '#4f46e5',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home-active.png',
      },
      {
        pagePath: 'pages/major-compare/index',
        text: '专业',
        iconPath: 'assets/tabbar/major.png',
        selectedIconPath: 'assets/tabbar/major-active.png',
      },
      {
        pagePath: 'pages/recommend/index',
        text: '推荐',
        iconPath: 'assets/tabbar/recommend.png',
        selectedIconPath: 'assets/tabbar/recommend-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/tabbar/profile.png',
        selectedIconPath: 'assets/tabbar/profile-active.png',
      },
    ],
  },
})
